import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import OpenAI from "openai";
import { useRef, useState } from "react";

export default function Home() {
  const apiKeyRef = useRef<HTMLInputElement>(null);
  const promptRef = useRef<HTMLInputElement>(null);
  const [loading, setLoading] = useState(false);
  const [image, setImage] = useState<string | null>(null);

  const handleSubmit = () => {
    if (loading) return;
    setLoading(true);
    const apiKey = apiKeyRef.current?.value;
    const prompt = promptRef.current?.value;

    if (!apiKey || !prompt) {
      return;
    }

    const openai = new OpenAI({
      apiKey,
      dangerouslyAllowBrowser: true,
    });

    openai.images
      .generate({
        prompt,
        model: "dall-e-3",
      })
      .then((res) => {
        if (res.data.length > 0 && res.data[0]?.url) {
          console.log("Image generated", res.data[0].url);
          setImage(res.data[0].url);
          // hard redirect user to the image in a new tab
          window.open(res.data[0].url, "_blank");
        } else {
          console.error("No image found in response", res);
        }
        setLoading(false);
      })
      .catch((err) => {
        console.error("Error generating image", err);
        setLoading(false);
      });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">DALL-E</span> API
          </h1>
          <div className="text-3xl font-bold tracking-tight text-white sm:text-[3rem]">
            Front-end by Evyn Jenkins
          </div>
          <div className="flex flex-col gap-4 text-black">
            <div className="rounded-md bg-gradient-to-b from-white to-slate-100 p-3">
              <label>API Key</label>
              <input
                type="text"
                className="w-full rounded-md border bg-white p-2 text-black"
                placeholder="API Key..."
                ref={apiKeyRef}
              />
            </div>
            <div className="rounded-md bg-gradient-to-b from-white to-slate-100 p-3">
              <label>Prompt</label>
              <input
                type="text"
                className="w-full rounded-md border bg-white p-2 text-black"
                placeholder="Prompt..."
                ref={promptRef}
              />
            </div>
            <button
              disabled={loading}
              className="rounded-md bg-gradient-to-b from-white to-slate-100 px-4 py-2 text-black transition-all duration-300 hover:from-cyan-300 hover:to-cyan-400"
              onClick={handleSubmit}
            >
              Submit
            </button>
          </div>
          <div>
            {loading && <div className="italic text-white">Loading...</div>}
            {image && (
              <a
                href={image}
                target="_blank"
                rel="noreferrer"
                className="animate-pulse rounded-full bg-gradient-to-b from-white to-slate-100 p-3 text-black transition-all duration-300 hover:from-cyan-300 hover:to-cyan-400"
              >
                Go to image
              </a>
            )}
            {/* {image && (
              <Image
                alt={"Generated DALL-E image"}
                src={image}
                width={500}
                height={500}
              />
            )} */}
          </div>
        </div>
      </main>
    </>
  );
}
